# .travis.yml file for hello-haskell
sudo: false

language: haskell

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

matrix:
  include:
    - ghc: '7.6'
    - ghc: '7.4'
      script: >
        make      GHCFLAGS="-fno-warn-unrecognised-pragmas" &&
        make test GHCFLAGS="-fno-warn-unrecognised-pragmas" &&
        make haddock HADDOCKFLAGS=
# see: https://docs.haskellstack.org/en/stable/travis_ci/
# see: https://github.com/hvr/multi-ghc-travis
    - ghc: '7.10'
      addons: {apt: {sources: hvr-ghc, packages: [cabal-install-1.22,ghc-7.10.1]}}
      before_install:
        - export PATH=/opt/ghc/7.10.1/bin:/opt/cabal/1.22/bin:$PATH
        - ghc --version
        - cabal --version
    - ghc: 'head'
      addons: {apt: {sources: hvr-ghc, packages: [cabal-install-head,ghc-head]}}
      before_install:
        - export PATH=/opt/ghc/head/bin:/opt/cabal/head/bin:$PATH
        - ghc --version
        - cabal --version

script:
  - make && make test && make haddock HADDOCKFLAGS=
  - cabal test

notifications:
  email:
    on_failure: change
