# Builds and tests this Haskell project on "GitHub Actions"
#
# 2021-2023  Rudy Matela
#
# some docs: https://github.com/haskell/actions/tree/main/setup
#
# The official haskell docker image: https://hub.docker.com/_/haskell
name: build
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - run: ghc hello.hs -o hello

      - name: Cache ~/.cabal/packages
        uses: actions/cache@v3
        with:
          path: ~/.cabal/packages
          key:          v1-${{ runner.os }}-cabal-packages-${{ hashFiles('hello.cabal') }}
          restore-keys: v1-${{ runner.os }}-cabal-packages-

      - name: Cache ~/.cabal and ~/.ghc
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal
            !~/.cabal/packages
            ~/.ghc
          key:          v1-${{ runner.os }}-cabal-ghc-latest-${{ hashFiles('hello.cabal') }}
          restore-keys: v1-${{ runner.os }}-cabal-ghc-latest-

      - run: du -hd3 ~/.cabal ~/.ghc || true

      - run: make --version

      - run: haddock --version || sudo apt-get install ghc-haddock
      - run: ghc     --version
      - run: cabal   --version
      - run: haddock --version
      - run: ghc-pkg list

      - name: Check out repository
        uses: actions/checkout@v3

      - run: git --version

      - run: cabal update
      - run: make install-dependencies

      - run: make
      - run: make test
      - run: make haddock
      - run: make test-sdist
      - run: make test-via-cabal
