# Haskell Workflow on GitHub actions
#
# 2021  Rudy Matela
#
# some docs: https://github.com/haskell/actions/tree/main/setup
name: Haskell Workflow
on: [push]
jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - {ghc: 'latest',  cabal: 'latest',  stack: 'latest'}
          - {ghc: '8.8',     cabal: '3.0',     stack: 'latest'}
          - {ghc: '8.6',     cabal: '2.4',     stack: 'latest'}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running on ${{ runner.os }} after a ${{ github.event_name }}"
      - run: echo "on branch ${{ github.ref }} of ${{ github.repository }}"

      - run: ghc --version
      - run: cabal --version
      - run: stack --version

      - name: Check out repository
        uses: actions/checkout@v2

      - run: cabal install leancheck || cabal v1-install leancheck

      - run: make
      - run: make test
      - run: make test-sdist
      - run: make haddock
      - run: cabal test --ghc-option=-O0
