# Haskell Workflow on GitHub actions
#
# 2021  Rudy Matela
#
# some docs: https://github.com/haskell/actions/tree/main/setup
name: Haskell Workflow
on: [push]
jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - { ghc: 'latest' , cabal: 'latest' }
          - { ghc: '8.8'    , cabal: '3.0'    }
          - { ghc: '8.6'    , cabal: '2.4'    }
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running on ${{ runner.os }} after a ${{ github.event_name }}"
      - run: echo "on branch ${{ github.ref }} of ${{ github.repository }}"
      - run: echo "with GHC ${{ matrix.ghc }} and Cabal ${{ matrix.cabal }}"

      - name: Setup Haskell's GHC and Cabal
        uses: haskell/actions/setup@v1
        with:
          ghc-version:   ${{ matrix.ghc   }}
          cabal-version: ${{ matrix.cabal }}

      - run: ghc   --version
      - run: hugs  --version
      - run: cabal --version
      - run: stack --version

      - name: Check out repository
        uses: actions/checkout@v2

      - run: make install-dependencies

      - run: make
      - run: make test
      - run: make test-sdist
      - run: make haddock
      - run: cabal test --ghc-option=-O0
