# Haskell Workflow on GitHub actions
#
# 2021  Rudy Matela
#
# some docs: https://github.com/haskell/actions/tree/main/setup
name: Haskell Workflow
on: [push]
jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - { ghc: 'latest' , cabal: 'latest' }
          - { ghc: '8.8'    , cabal: '3.0'    }
          - { ghc: '8.6'    , cabal: '2.4'    }
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running on ${{ runner.os }} after a ${{ github.event_name }}"
      - run: echo "on branch ${{ github.ref }} of ${{ github.repository }}"
      - run: echo "with GHC ${{ matrix.ghc }} and Cabal ${{ matrix.cabal }}"

      - name: Setup Haskell's GHC and Cabal
        uses: haskell/actions/setup@v1
        with:
          ghc-version:   ${{ matrix.ghc   }}
          cabal-version: ${{ matrix.cabal }}

      - run: ghc   --version
      - run: cabal --version

      - name: Check out repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal
            ~/.ghc
          key: v1-${{ runner.os }}-cabal-${{ hashFiles('hello.cabal') }}
          restore-keys: |
            v1-${{ runner.os }}-cabal-

      - run: du -hd3 ~/.cabal ~/.ghc || true

      - run: make install-dependencies

      - run: make
      - run: make test
      - run: make haddock
      - run: make test-sdist
      - run: make test-via-cabal

  build-and-test-with-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Haskell's GHC and Cabal as required by current Stackage LTS
        uses: haskell/actions/setup@v1
        with: # lts-17.9
          ghc-version: '8.10.4'
          cabal-version: '3.2'
      - name: Check out repository
        uses: actions/checkout@v2
      - run: make test-via-stack
